### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by josephsdavid** [josephsdavid/neorg-snippets#1]
Here we will track all the things we need to do to make this useful to others (other than me 😈 )
- [ ] Decide on whether this is a neorg extension, or we close this repo up and make a PR to norg and have luasnip integration #6
- [ ] #5
- [ ] #4
- [ ] Add more helpful snippets

**Comment by josephsdavid** [comment]
- [ ] combine dynamic repeated character generation with recursive list generation (or equivalent fix)
